services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./rtod/models:/app/rtod/models:ro
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
