apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rtod-backend-hpa
  namespace: rtod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rtod-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rtod-frontend-hpa
  namespace: rtod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rtod-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

