name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check .

      - name: Run tests (mock mode)
        env:
          TF_CPP_MIN_LOG_LEVEL: "3"
        run: |
          pytest -q

      - name: Build backend image
        run: |
          docker build -t rtod-backend -f Dockerfile.backend .

      - name: Build frontend image
        run: |
          docker build -t rtod-frontend -f Dockerfile.frontend .
